### ISSUE TITLE
rspecテスト実行時のuninitialized constant ActiveRecordとテスト環境の構築

### ISSUE THREAD

**Issue by misakiyashima** [misakiyashima/graduation_exam#80]
1.テスト環境における MySQLコンテナの接続問題
・MySQLの環境変数設定やデータボリュームの不整合が原因。
・dbコンテナが不健康（unhealthy）な状態で正しく動作していなかった。

→・Dockerネットワークとデータボリュームのリセット・コンテナの再構築を実施。
・テスト環境におけるMySQLの環境変数を確認し、MYSQL_ROOT_PASSWORDが正しく設定されるよう修正。
docker-compose.yml
```
db:
  image: mysql:8.0
  environment:
    TZ: Asia/Tokyo
    MYSQL_ROOT_PASSWORD: password
```

2. ActiveRecord接続エラー
・Railsがconfig/database.ymlや環境変数を正しく読み込めていなかった。
・RailsのActiveRecord::Base.connectionで接続は試みられていたものの、接続が有効化されず。

→・Railsコンソールで詳細なエラーメッセージを確認・追跡。
```
begin
  ActiveRecord::Base.connection
rescue => e
  puts "Error message: #{e.message}"
  puts "Backtrace:"
  puts e.backtrace.join("\n")
end
```
```
ActiveRecord::Base.connection.active?
```

・spec/spec_helper.rbおよびspec/rails_helper.rbに明示的なActiveRecord接続設定を追加。
```
require 'active_record'
ActiveRecord::Base.establish_connection(
  Rails.configuration.database_configuration['test']
)
```

3. RSpec環境の不整合
・RSpecがRails環境やActiveRecord設定を正しく読み込めていなかった。
・spec/spec_helper.rbとspec/rails_helper.rbに必要な初期化コードが不足。

→・spec/spec_helper.rbおよびspec/rails_helper.rbに以下を追加、明示的に記述し、接続設定を確立。
```
config.before(:suite) do
  ActiveRecord::Base.connection
  Rails.application.load_tasks
  Rake::Task['db:test:prepare'].invoke
end
```

・テスト用データベースの準備
```
docker compose exec web rails db:prepare
```

4. データベース環境の確認と準備
・テストデータベースのマイグレーションや準備が不足。
・config/database.ymlへ明示的にtest環境を記載。
```
test:
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password
  host: db
  database: myapp_test
  port: 3306
```

☆テスト用データベースの作成・テスト用環境変数の設定
→test環境からmysqlへアクセス可能に。
☆spec/spec_helper.rbおよびspec/rails_helper.rbにactiveレコードへの接続方法を明示的に記載
→テスト環境でrailsからactiveレコードにアクセス可能に。RSpecがRails環境やActiveRecord設定を正しく読み込み可能に。
